"""Bilibili Cookie 的公共读取逻辑。

支持两种磁盘格式，方便不同工具导出的文件都能直接用：

1. Netscape 格式，每行 7 个制表符分隔字段，由「Get cookies.txt」这类浏览器扩展
   导出，也是 yt-dlp 唯一接受的格式。
2. 请求头格式，即 ``name=value`` 用分号或换行分隔，直接从浏览器开发者工具里复制。

本模块从不打印任何 Cookie 值。
"""

from __future__ import annotations

import re
import tempfile
import time
from pathlib import Path


NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n"
DEFAULT_DOMAIN = ".bilibili.com"


def parse_cookie_text(text: str) -> dict[str, str]:
    """从两种支持的格式中解析出 Cookie 名与值的映射。"""
    cookies: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("#") and not line.startswith("#HttpOnly_"):
            continue
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_"):]
        if "\t" in line:
            fields = line.split("\t")
            if len(fields) >= 7 and fields[5]:
                cookies[fields[5].strip()] = fields[6].strip()
            continue
        for pair in line.split(";"):
            item = pair.strip()
            if not item or "=" not in item:
                continue
            name, _, value = item.partition("=")
            name = name.strip()
            if name:
                cookies[name] = value.strip()
    return cookies


def load_cookies(path: Path | None) -> dict[str, str]:
    if path is None or not path.is_file():
        return {}
    try:
        return parse_cookie_text(path.read_text(encoding="utf-8", errors="replace"))
    except OSError:
        return {}


def cookie_header(cookies: dict[str, str]) -> str:
    return "; ".join(f"{name}={value}" for name, value in cookies.items() if name)


def netscape_text(cookies: dict[str, str], domain: str = DEFAULT_DOMAIN) -> str:
    expiry = int(time.time()) + 365 * 24 * 3600
    lines = [NETSCAPE_HEADER, "# Generated by Mikuxperia sync. Do not share.\n"]
    for name, value in cookies.items():
        if not name:
            continue
        lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}\n")
    return "".join(lines)


def is_netscape_file(path: Path | None) -> bool:
    if path is None or not path.is_file():
        return False
    try:
        for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw_line.strip()
            if line and not line.startswith("#") and "\t" in line:
                return len(line.split("\t")) >= 7
    except OSError:
        return False
    return False


def netscape_file_for(path: Path | None) -> tuple[Path | None, Path | None]:
    """返回一个 yt-dlp 可用的 Netscape 格式 Cookie 文件。

    返回值的第二项是需要调用方自行删除的临时文件；原文件本来就是 Netscape
    格式时，第二项为 None。
    """
    cookies = load_cookies(path)
    if not cookies:
        return None, None
    if is_netscape_file(path):
        return path, None
    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", suffix=".cookies.txt", delete=False, newline="\n"
    )
    try:
        handle.write(netscape_text(cookies))
    finally:
        handle.close()
    temporary = Path(handle.name)
    try:
        temporary.chmod(0o600)
    except OSError:
        pass
    return temporary, temporary


def describe(path: Path | None) -> dict:
    """概述一个 Cookie 文件的状态，不暴露任何 Cookie 值。"""
    cookies = load_cookies(path)
    required = ("SESSDATA",)
    optional = ("bili_jct", "DedeUserID", "buvid3")
    return {
        "count": len(cookies),
        "names": sorted(cookies),
        "format": "netscape" if is_netscape_file(path) else ("header" if cookies else "unknown"),
        "has_sessdata": all(name in cookies for name in required),
        "missing_optional": [name for name in optional if name not in cookies],
    }
